# This script uses selenium and headless firefox to get a specific cookie
# generated by the CSOB bank website.
# Headless firefox is running on a docker container on "localhost:4444".
from time import sleep
from selenium import webdriver


def get_cookie(address, host_port) -> str:
    # It imports the webdriver module from the selenium package.
    firefox_options = webdriver.FirefoxOptions()
    firefox_options.headless = True

    driver = webdriver.Remote(
        command_executor=f"http://{address}:{host_port}",
        options=firefox_options
    )

    driver.get("https://www.csob.cz/portal/robots.txt")

    sleep(5)

    csob_cookie = driver.get_cookie("TSPD_101")["value"]

    driver.quit()

    return csob_cookie


get_cookie(address="localhost", host_port="4445")
