---
title: "2023 Czech Presidential Election Financing"
author: "Ondrej Pekacek & TI CZ"
date: "`r format(Sys.Date(),'%d. %m. %Y')`"
output: 
  flexdashboard::flex_dashboard:
    logo: "doc/logo_ti.png"
    theme: readable
    includes:
      in_header: "doc/header.html"
    orientation: columns
    vertical_layout: fill
    source_code: https://github.com/opop999/TI_monitoring_transparent_accounts_2023
    navbar:
      - {title: "Project", icon: "ion-information-circled", href: "https://www.transparentnivolby.cz/"}
      - {title: "Author", icon: "ion-social-linkedin", href: "https://www.linkedin.com/in/ondrej-pekacek"}
      - {title: "Data: FIO", icon: "ion-cloud", href: "https://www.fio.cz/bankovni-sluzby/bankovni-ucty/transparentni-ucet/vypis-transparentnich-uctu"}
      - {title: "Data: CSAS", icon: "ion-cloud", href: "https://www.csas.cz/cs/transparentni-ucty#/"}
      - {title: "Data: KB", icon: "ion-cloud", href: "https://www.kb.cz/cs/transparentni-ucty"}
      - {title: "Data: CSOB", icon: "ion-cloud", href: "https://www.csob.cz/portal/firmy/bezne-ucty/transparentni-ucty"}
---

```{css, echo=FALSE}
.navbar-inverse {
    background-color: #e8efff;
}
```

```{js, echo=FALSE}
// Add pull-left class to logo
document.querySelector("span.navbar-logo").classList.add("pull-left")
```

```{r setup, include=FALSE}
# Disable scientific notation of numbers
options(scipen = 999)

# Package names
packages <- c("dplyr", "ggplot2", "forcats", "tidyr", "reactable", "reactablefmtr", "stringr", "plotly", "flexdashboard", "htmlwidgets")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# Specify directory with datasets
directory_datasets <- "data/summary_tables"
  
total_spending <- readRDS(file = file.path(directory_datasets, "total_spending.rds"))
time_spending <- readRDS(file = file.path(directory_datasets, "time_spending.rds"))
total_income <- readRDS(file = file.path(directory_datasets, "total_income.rds"))
time_income <- readRDS(file = file.path(directory_datasets, "time_income.rds"))

# Election date for vertical line in the time-plots
election_date <- as.Date("2023-01-27")

# Graph zoom date end & beginning
start_date <- as.Date("2022-08-01")
end_date <- as.Date("2023-01-27")

# Select appropriate palette for individual html plots to be exported
# custom_palette <- brewer.pal(8, "Dark2") 

#### VERIFY IF NEEDED ######
# Extract name of parties to be used in labeling
# parties_names <- levels(time_spending$entity) 
# parties_names_title <- parties_names %>% 
#   str_replace_all(pattern = "_", replacement = " ") %>% 
#   str_to_title()

```

Summaries
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **SPENDING** {.no-mobile}

```{r}
plot_total_spending <- ggplotly(
  total_spending %>%
    mutate(
      entity = str_to_title(str_replace_all(entity, pattern = "_", replacement = " ")),
      entity = reorder(entity, total_spend_million)
    ) %>% 
    ggplot(aes(x = total_spend_million, y = entity, fill = per_transaction_avg_spend_thousand, text = paste(
          "Election candidate:",
          entity,
         "<br>Total spending:",
         total_spend_million, "million CZK",
         "<br>Per transaction avg spend:",
         per_transaction_avg_spend_thousand, "thousand CZK"
         
        ))) +
    geom_col() +
    scale_x_continuous(
      breaks = seq(0, 200, 5),
      labels = seq(0, 200, 5)
    ) +
    scale_fill_gradient(
      low = "#FFF0F3",
      high = "#800F2F",
      limits = c(0, 2000),
      breaks = c(0, 500, 1000, 1500, 2000)
    ) +
    theme_minimal() +
    labs(x = "CZK million",
         y = element_blank(),
         fill = "Per transaction (CZK thousands)",
         title = paste("Total spending on transparent accounts since", format(start_date, "%d.%m.%Y"))),
    tooltip = "text"
) %>%
  config(displaylogo = FALSE)

plot_total_spending
```

### **INCOME** {.no-mobile}

```{r}
plot_total_income <- ggplotly(
  total_income %>%
    mutate(
      entity = str_to_title(str_replace_all(entity, pattern = "_", replacement = " ")),
      entity = reorder(entity, total_income_million)
    ) %>% 
    ggplot(aes(x = total_income_million, y = entity, fill = per_transaction_avg_income_thousand, text = paste(
          "Election candidate:",
          entity,
         "<br>Total income:",
         total_income_million, "million CZK",
         "<br>Per transaction avg income:",
         per_transaction_avg_income_thousand, "thousand CZK"
         
        ))) +
    geom_col() +
    scale_x_continuous(
      breaks = seq(0, 200, 5),
      labels = seq(0, 200, 5)
    ) +
    scale_fill_gradient(
      low = "#CAF0F8",
      high = "#023e8a",
      limits = c(0, 2000),
      breaks = c(0, 500, 1000, 1500, 2000)
    ) +
    theme_minimal() +
    labs(x = "CZK million",
         y = element_blank(),
         fill = "Per transaction (CZK thousands)",
         title = paste("Total income on transparent accounts since", format(start_date, "%d.%m.%Y"))),
    tooltip = "text"
) %>%
  config(displaylogo = FALSE)

plot_total_income
```


### **SUMMARY TABLE** {.no-mobile}

```{r}
full_join(total_income, total_spending, by = "entity") %>%
  mutate(
  entity = str_to_title(str_replace_all(entity, pattern = "_", replacement = " ")),
    across(where(is.numeric), ~replace_na(.x, 0))
  )  %>% 
  reactable(
    defaultPageSize = 15,
    theme = nytimes(),
    highlight = TRUE,
    defaultSorted = c("entity"),
    filterable = TRUE,
    striped = TRUE,
    defaultColDef = colDef(filterable = FALSE),
    columns = list(
       "entity" = colDef(name = "entity", sticky = "left", filterable = TRUE),
       "total_transactions_income" = colDef(name = "Nr. Transactions Income")
    #   "unique_ads" = colDef(name = "Unique Ads"),
    #   "avg_words" = colDef(name = "Average Words"),
    #   "avg_spend" = colDef(name = "Spend", format = colFormat(prefix = "CZK ", separators = TRUE, digits = 0)),
    #   "per_ad_avg_spend" = colDef(name = "Per Ad Spend", format = colFormat(prefix = "CZK ", separators = TRUE, digits = 0)),
    #   "total_avg_impressions" = colDef(name = "Total Impressions", format = colFormat(separators = TRUE, digits = 0)),
    #   "per_ad_avg_impression" = colDef(name = "Per Ad Impressions", format = colFormat(separators = TRUE, digits = 0)),
    #   "avg_ad_min_audience" = colDef(name = "Average Ad Min Audience", format = colFormat(separators = TRUE, digits = 0)),
    #   "avg_ad_runtime" = colDef(name = "Average Runtime", format = colFormat(suffix = " days"))
    # )
  ))
```



Column {.tabset .mobile}
-----------------------------------------------------------------------

### **SPENDING** 

```{r}

```


### **INCOME** 

```{r}

```


Trends
=====================================

Column {.tabset}
-----------------------------------------------------------------------

### **SPENDING OVER TIME** {.no-mobile}

```{r}

```

### **SPENDING WEEKLY** {.no-mobile}

```{r}

```


### **INCOME OVER TIME** {.no-mobile}

```{r}

```

### **INCOME WEEKLY** {.no-mobile}

```{r}

```

Column {.tabset .mobile}
-----------------------------------------------------------------------

### **SPENDING OVER TIME**

```{r}

```

### **SPENDING WEEKLY**

```{r}

```

### **INCOME OVER TIME**

```{r}

```

### **INCOME WEEKLY**

```{r}

```


<!-- # Specify directory with datasets -->
<!-- directory_datasets <- "data/" -->

<!-- # Import datasets created in the previous script -->
<!-- summary_dataset <- readRDS(file = paste0(directory_datasets, "summary_tables/merged_summary.rds")) -->
<!-- time_dataset <- readRDS(file = paste0(directory_datasets, "summary_tables/time_summary.rds")) -->
<!-- regional_spenders <- readRDS(file = paste0(directory_datasets, "summary_tables/regional_spenders.rds")) -->

<!-- # Select TOP 10 biggest spenders for plotting -->
<!-- top_10_spenders <- summary_dataset %>% -->
<!--   slice_max(avg_spend, n = 10) %>% -->
<!--   select(page_name, page_id, avg_spend) -->

<!-- # Election date for vertical line in the time-plots -->
<!-- election_date <- as.Date("2023-01-27") -->

<!-- # Graph zoom date end & beginning -->
<!-- start_date <- as.Date("2022-08-01") -->
<!-- end_date <- as.Date("2023-01-27") -->

<!-- # Specify output directory for individual plots -->
<!-- directory <- "data/html_plots" -->

<!-- # Check whether output directory exists to save individual plots -->
<!-- if (!dir.exists(directory)) { -->
<!--   dir.create(directory) -->
<!-- } else { -->
<!--   print("Output directory already exists") -->
<!-- } -->
<!-- ``` -->

<!-- Ads -->
<!-- ===================================== -->

<!-- Column {.tabset} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### **TOTAL ADS** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_total_ads <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, total_ads)) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = total_ads, -->
<!--         y = page_name, -->
<!--         fill = percent_unique, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Total ads:", -->
<!--           total_ads, -->
<!--           "<br>Proportion unique ads:", -->
<!--           percent_unique * 100, -->
<!--           "%" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col() + -->
<!--     scale_fill_gradient( -->
<!--       low = "#fbe8e7", -->
<!--       high = "#db1d0b", -->
<!--       limits = c(0, 1), -->
<!--       breaks = c(0, 0.25, 0.50, 0.75, 1), -->
<!--       labels = c("0%", "25%", "50%", "75%", "100%") -->
<!--     ) + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 5000, 250), -->
<!--       labels = seq(0, 5000, 250) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab("Total ads") + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "Proportion unique ads") + -->
<!--     ggtitle(paste( -->
<!--       "Total ads of top 30 spenders since", -->
<!--       format(start_date, "%d.%m.%Y") -->
<!--     )), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_total_ads -->

<!-- # saveWidget(plot_total_ads, file = paste0(directory, "/plot_total_ads.html")) -->
<!-- ``` -->

<!-- ### **TOTAL SPENDING** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_total_spending <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate( -->
<!--       avg_spend_1000 = round(avg_spend / 1000, digits = 0), -->
<!--       per_ad_avg_spend_1000 = round(per_ad_avg_spend / 1000, digits = 1), -->
<!--       page_name = reorder(page_name, avg_spend) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes(x = avg_spend_1000, y = page_name, fill = per_ad_avg_spend_1000, text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Total spend:", -->
<!--         avg_spend_1000, "thousand CZK", -->
<!--         "<br>Per ad avg spend:", -->
<!--         per_ad_avg_spend_1000, "thousand CZK" -->
<!--       )) -->
<!--     ) + -->
<!--     geom_col() + -->
<!--     scale_fill_gradient2( -->
<!--       low = "#cddae5", -->
<!--       mid = "#03457f", -->
<!--       high = "#023766", -->
<!--       midpoint = 25, -->
<!--       limits = c(0, 50) -->
<!--     ) + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 5000, 250), -->
<!--       labels = seq(0, 5000, 250) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab("Total spend (CZK thousands)") + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "Per ad (CZK thousands)") + -->
<!--     ggtitle(paste( -->
<!--       "Spending on ads of top 30 spenders since", -->
<!--       format(start_date, "%d.%m.%Y") -->
<!--     )), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_total_spending -->

<!-- # saveWidget(plot_total_spending, file = paste0(directory, "/plot_total_spending.html")) -->
<!-- ``` -->

<!-- ### **AD LENGTH** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_ad_length <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, avg_words)) %>% -->
<!--     ggplot(aes( -->
<!--       x = avg_words, y = page_name, -->
<!--       text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Avg length per ad:", -->
<!--         avg_words, "words" -->
<!--       ) -->
<!--     )) + -->
<!--     geom_col(fill = "#320266") + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 1500, 50), -->
<!--       labels = seq(0, 1500, 50) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab("Number of Words") + -->
<!--     ylab(element_blank()) + -->
<!--     ggtitle( -->
<!--       paste( -->
<!--         "Average ad length in words of top 30 spenders since", -->
<!--         format(start_date, "%d.%m.%Y") -->
<!--       ) -->
<!--     ), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_ad_length -->

<!-- # saveWidget(plot_ad_length, file = paste0(directory, "/plot_ad_length.html")) -->
<!-- ``` -->

<!-- ### **AD RUNTIME** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_ad_runtime <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, avg_ad_runtime)) %>% -->
<!--     ggplot(aes( -->
<!--       x = avg_ad_runtime, y = page_name, text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Avg runtime:", -->
<!--         avg_ad_runtime, "days" -->
<!--       ) -->
<!--     )) + -->
<!--     geom_col(fill = "#026663") + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 150, 5), -->
<!--       labels = seq(0, 150, 5) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab("Days") + -->
<!--     ylab(element_blank()) + -->
<!--     ggtitle( -->
<!--       paste( -->
<!--         "Average ad runtime of top 30 spenders since", -->
<!--         format(start_date, "%d.%m.%Y") -->
<!--       ) -->
<!--     ), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_ad_runtime -->

<!-- # saveWidget(plot_ad_runtime, file = paste0(directory, "/plot_ad_runtime.html")) -->
<!-- ``` -->

<!-- ### **IMPRESSIONS** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_ad_impressions <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate( -->
<!--       avg_impressions_million = round(total_avg_impressions / 1000000, digits = 3), -->
<!--       per_ad_avg_impressions_1000 = round(per_ad_avg_impression / 1000, digits = 1), -->
<!--       page_name = reorder(page_name, avg_impressions_million) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = avg_impressions_million, y = page_name, fill = per_ad_avg_impressions_1000, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Total impressions:", -->
<!--           avg_impressions_million, "million", -->
<!--           "<br>Avg impressions per ad:", -->
<!--           per_ad_avg_impressions_1000, "thousand" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col() + -->
<!--     scale_fill_gradient2( -->
<!--       low = "#e7fbe8", -->
<!--       mid = "#089914", -->
<!--       high = "#011603", -->
<!--       midpoint = 250, -->
<!--       limits = c(0, 500) -->
<!--     ) + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 1000, 5), -->
<!--       labels = seq(0, 1000, 5) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab("Total impressions (millions)") + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "Per Ad impressions (thousands)") + -->
<!--     ggtitle(paste( -->
<!--       "Total ads impressions of top 30 spenders since", -->
<!--       format(start_date, "%d.%m.%Y") -->
<!--     )), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_ad_impressions -->

<!-- # saveWidget(plot_ad_impressions, file = paste0(directory, "/plot_ad_impressions.html")) -->
<!-- ``` -->

<!-- ### **AVERAGE AUDIENCE** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_ad_audience <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate( -->
<!--       avg_ad_min_audience_1000 = round(avg_ad_min_audience / 1000, digits = 0), -->
<!--       page_name = reorder(page_name, avg_ad_min_audience_1000) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = avg_ad_min_audience_1000, -->
<!--         y = page_name, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Average minimal audience:", -->
<!--           avg_ad_min_audience_1000, "thousand" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col(fill = "#94d9ee") + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 2000, 100), -->
<!--       labels = seq(0, 2000, 100) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab("Average targeted audience size (thousands)") + -->
<!--     ylab(element_blank()) + -->
<!--     ggtitle( -->
<!--       paste( -->
<!--         "Average minimal estimated audience of top 30 spenders since", -->
<!--         format(start_date, "%d.%m.%Y") -->
<!--       ) -->
<!--     ), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_ad_audience -->

<!-- # saveWidget(plot_ad_audience, file = paste0(directory, "/plot_ad_audience.html")) -->
<!-- ``` -->

<!-- ### **ADS SUMMARY TABLE** {.no-mobile} -->

<!-- ```{r} -->
<!-- summary_dataset %>% -->
<!--   select(1:12) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef(filterable = FALSE), -->
<!--     columns = list( -->
<!--       "page_name" = colDef(name = "Page Name", sticky = "left", filterable = TRUE, width = 120), -->
<!--       "page_id" = colDef(name = "Page ID", sticky = "left", width = 120), -->
<!--       "total_ads" = colDef(name = "Total Ads", ), -->
<!--       "unique_ads" = colDef(name = "Unique Ads"), -->
<!--       "percent_unique" = colDef(name = "Proportion Unique", format = colFormat(percent = TRUE, digits = 1)), -->
<!--       "avg_words" = colDef(name = "Average Words"), -->
<!--       "avg_spend" = colDef(name = "Spend", format = colFormat(prefix = "CZK ", separators = TRUE, digits = 0)), -->
<!--       "per_ad_avg_spend" = colDef(name = "Per Ad Spend", format = colFormat(prefix = "CZK ", separators = TRUE, digits = 0)), -->
<!--       "total_avg_impressions" = colDef(name = "Total Impressions", format = colFormat(separators = TRUE, digits = 0)), -->
<!--       "per_ad_avg_impression" = colDef(name = "Per Ad Impressions", format = colFormat(separators = TRUE, digits = 0)), -->
<!--       "avg_ad_min_audience" = colDef(name = "Average Ad Min Audience", format = colFormat(separators = TRUE, digits = 0)), -->
<!--       "avg_ad_runtime" = colDef(name = "Average Runtime", format = colFormat(suffix = " days")) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->

<!-- Column {.tabset .mobile} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### **TOTAL ADS**  -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, total_ads)) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = total_ads, -->
<!--         y = page_name, -->
<!--         fill = percent_unique, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Total ads:", -->
<!--           total_ads, -->
<!--           "<br>Proportion unique ads:", -->
<!--           percent_unique * 100, -->
<!--           "%" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col() + -->
<!--     scale_fill_gradient( -->
<!--       low = "#fbe8e7", -->
<!--       high = "#db1d0b", -->
<!--       limits = c(0, 1), -->
<!--       breaks = c(0, 0.25, 0.50, 0.75, 1), -->
<!--       labels = c("0%", "25%", "50%", "75%", "100%") -->
<!--     ) + -->
<!--     scale_y_discrete(label = function(x) str_trunc(x, 16)) + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 5000, 500), -->
<!--       labels = seq(0, 5000, 500) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "Proportion unique ads"), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->
<!-- ``` -->

<!-- ### **TOTAL SPENDING**  -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate( -->
<!--       avg_spend_1000 = round(avg_spend / 1000, digits = 0), -->
<!--       per_ad_avg_spend_1000 = round(per_ad_avg_spend / 1000, digits = 1), -->
<!--       page_name = reorder(page_name, avg_spend) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes(x = avg_spend_1000, y = page_name, fill = per_ad_avg_spend_1000, text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Total spend:", -->
<!--         avg_spend_1000, "thousand CZK", -->
<!--         "<br>Per ad avg spend:", -->
<!--         per_ad_avg_spend_1000, "thousand CZK" -->
<!--       )) -->
<!--     ) + -->
<!--     geom_col() + -->
<!--     scale_fill_gradient2( -->
<!--       low = "#cddae5", -->
<!--       mid = "#03457f", -->
<!--       high = "#023766", -->
<!--       midpoint = 25, -->
<!--       limits = c(0, 50) -->
<!--     ) + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 5000, 500), -->
<!--       labels = seq(0, 5000, 500) -->
<!--     ) + -->
<!--     scale_y_discrete(label = function(x) str_trunc(x, 16)) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "Per ad (CZK thousands)"), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->

<!-- ### **AD LENGTH**  -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, avg_words)) %>% -->
<!--     ggplot(aes( -->
<!--       x = avg_words, y = page_name, -->
<!--       text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Avg length per ad:", -->
<!--         avg_words, "words" -->
<!--       ) -->
<!--     )) + -->
<!--     geom_col(fill = "#320266") + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 1500, 100), -->
<!--       labels = seq(0, 1500, 100) -->
<!--     ) + -->
<!--     scale_y_discrete(label = function(x) str_trunc(x, 16)) + -->
<!--     theme_minimal() + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->

<!-- ### **AD RUNTIME**  -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, avg_ad_runtime)) %>% -->
<!--     ggplot(aes( -->
<!--       x = avg_ad_runtime, -->
<!--       y = page_name, -->
<!--       text = paste("Page:", -->
<!--                    page_name, -->
<!--                    "<br>Avg runtime:", -->
<!--                    avg_ad_runtime, "days") -->
<!--     )) + -->
<!--     geom_col(fill = "#026663") + -->
<!--     scale_x_continuous(breaks = seq(0, 150, 5), -->
<!--                        labels = seq(0, 150, 5)) + -->
<!--     scale_y_discrete( -->
<!--       label = function(x) -->
<!--         str_trunc(x, 16) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->
<!-- ``` -->

<!-- ### **IMPRESSIONS**  -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate( -->
<!--       avg_impressions_million = round(total_avg_impressions / 1000000, digits = 3), -->
<!--       per_ad_avg_impressions_1000 = round(per_ad_avg_impression / 1000, digits = 1), -->
<!--       page_name = reorder(page_name, avg_impressions_million) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = avg_impressions_million, -->
<!--         y = page_name, -->
<!--         fill = per_ad_avg_impressions_1000, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Total impressions:", -->
<!--           avg_impressions_million, -->
<!--           "million", -->
<!--           "<br>Avg impressions per ad:", -->
<!--           per_ad_avg_impressions_1000, -->
<!--           "thousand" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col() + -->
<!--     scale_fill_gradient2( -->
<!--       low = "#e7fbe8", -->
<!--       mid = "#089914", -->
<!--       high = "#011603", -->
<!--       midpoint = 250, -->
<!--       limits = c(0, 500) -->
<!--     ) + -->
<!--     scale_x_continuous(breaks = seq(0, 1000, 10), -->
<!--                        labels = seq(0, 1000, 10)) + -->
<!--     scale_y_discrete( -->
<!--       label = function(x) -->
<!--         str_trunc(x, 16) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "Per Ad impressions (thousands)"), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->

<!-- ### **AVERAGE AUDIENCE**  -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate( -->
<!--       avg_ad_min_audience_1000 = round(avg_ad_min_audience / 1000, digits = 0), -->
<!--       page_name = reorder(page_name, avg_ad_min_audience_1000) -->
<!--     ) %>% -->
<!--     ggplot(aes( -->
<!--       x = avg_ad_min_audience_1000, -->
<!--       y = page_name, -->
<!--       text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Average minimal audience:", -->
<!--         avg_ad_min_audience_1000, -->
<!--         "thousand" -->
<!--       ) -->
<!--     )) + -->
<!--     geom_col(fill = "#94d9ee") + -->
<!--     scale_x_continuous( -->
<!--       breaks = seq(0, 2000, 250), -->
<!--       labels = seq(0, 2000, 250) -->
<!--     ) + -->
<!--     scale_y_discrete( -->
<!--       label = function(x) -->
<!--         str_trunc(x, 16) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->

<!-- ### **ADS SUMMARY TABLE**  -->

<!-- ```{r} -->
<!-- summary_dataset %>% -->
<!--   select(1:12) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef(filterable = FALSE), -->
<!--     columns = list( -->
<!--       "page_name" = colDef(name = "Page Name", sticky = "left", filterable = TRUE, width = 70), -->
<!--       "page_id" = colDef(name = "Page ID", sticky = "left", width = 50), -->
<!--       "total_ads" = colDef(name = "Total Ads", ), -->
<!--       "unique_ads" = colDef(name = "Unique Ads"), -->
<!--       "percent_unique" = colDef(name = "Proportion Unique", format = colFormat(percent = TRUE, digits = 1)), -->
<!--       "avg_words" = colDef(name = "Average Words"), -->
<!--       "avg_spend" = colDef(name = "Spend", format = colFormat(prefix = "CZK ", separators = TRUE, digits = 0)), -->
<!--       "per_ad_avg_spend" = colDef(name = "Per Ad Spend", format = colFormat(prefix = "CZK ", separators = TRUE, digits = 0)), -->
<!--       "total_avg_impressions" = colDef(name = "Total Impressions", format = colFormat(separators = TRUE, digits = 0)), -->
<!--       "per_ad_avg_impression" = colDef(name = "Per Ad Impressions", format = colFormat(separators = TRUE, digits = 0)), -->
<!--       "avg_ad_min_audience" = colDef(name = "Average Ad Min Audience", format = colFormat(separators = TRUE, digits = 0)), -->
<!--       "avg_ad_runtime" = colDef(name = "Average Runtime", format = colFormat(suffix = " days")) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->


<!-- Trends -->
<!-- ===================================== -->

<!-- Column {.tabset} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### **SPENDING OVER TIME** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_spend_over_time <- ggplotly( -->
<!--   time_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     mutate( -->
<!--       ad_creation_time_week = as.Date(cut( -->
<!--         ad_creation_time, -->
<!--         breaks = "week", -->
<!--         start.on.monday = TRUE -->
<!--       )) + 6, -->
<!--       cumulative_spend_million = round((cumulative_spend / 1000000), digits = 3) -->
<!--     ) %>% -->
<!--     group_by(page_name, ad_creation_time_week) %>% -->
<!--     summarise(end_of_week_million_spend = max(cumulative_spend_million)) %>% -->
<!--     ungroup() %>% -->
<!--     ggplot( -->
<!--       aes(x = ad_creation_time_week, y = end_of_week_million_spend, color = page_name) -->
<!--     ) + -->
<!--     geom_line() + -->
<!--     geom_point(size = 0.8, aes(text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Week:", -->
<!--       ad_creation_time_week, -->
<!--       "<br>Cumulative spend:", -->
<!--       end_of_week_million_spend, "million CZK" -->
<!--     ))) + -->
<!--     geom_vline( -->
<!--       aes(xintercept = as.numeric(election_date)), -->
<!--       color = "#563a3a", -->
<!--       linetype = 2, -->
<!--       size = 0.2 -->
<!--     ) + -->
<!--     geom_text( -->
<!--       aes(x = election_date, y = 0, label = "elections"), -->
<!--       color = "#22209F", -->
<!--       vjust = -1, -->
<!--       size = 3, -->
<!--       fontface = "bold", -->
<!--       check_overlap = TRUE -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 5, 0.25), -->
<!--       labels = seq(0, 5, 0.25) -->
<!--     ) + -->
<!--     scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") + -->
<!--     coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) + -->
<!--     theme( -->
<!--       legend.title = element_blank(), -->
<!--       axis.text.x = element_text(angle = 45, hjust = 1) -->
<!--     ) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab("CZK million") + -->
<!--     labs(color = "") + -->
<!--     ggtitle(paste( -->
<!--       "Spending on ads of top 10 spenders since", -->
<!--       format(start_date, "%d.%m.%Y") -->
<!--     )), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_spend_over_time -->

<!-- # saveWidget(plot_spend_over_time, file = paste0(directory, "/plot_spend_over_time.html")) -->
<!-- ``` -->

<!-- ### **SPENDING WEEKLY** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_spend_weekly <- ggplotly( -->
<!--   time_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     mutate( -->
<!--       end_of_week = as.Date(cut(ad_creation_time, breaks = "week", start.on.monday = TRUE)) + 6, -->
<!--     ) %>% -->
<!--     group_by(page_name, end_of_week) %>% -->
<!--     summarise(by_week_thousands_spend = round(sum(avg_spend) / 1000, digits = 0)) %>% -->
<!--     ungroup() %>% -->
<!--     ggplot(aes( -->
<!--       x = end_of_week, y = by_week_thousands_spend, fill = page_name, -->
<!--       text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Week:", -->
<!--         end_of_week, -->
<!--         "<br>Weekly spend:", -->
<!--         by_week_thousands_spend, "thousand CZK" -->
<!--       ) -->
<!--     )) + -->
<!--     geom_col(width = 5.5) + -->
<!--     geom_vline(xintercept = as.numeric(election_date), color = "#563a3a", linetype = 2, size = 0.2) + -->
<!--     geom_text(aes(x = election_date, y = 0, label = "elections"), color = "#22209F", vjust = -1, size = 3, fontface = "bold", check_overlap = TRUE) + -->
<!--     theme_minimal() + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 5000, 100), -->
<!--       labels = seq(0, 5000, 100) -->
<!--     ) + -->
<!--     scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") + -->
<!--     coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) + -->
<!--     theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab("CZK thousand") + -->
<!--     labs(fill = "") + -->
<!--     ggtitle(paste("Weekly spending on ads of top 10 spenders since", format(start_date, "%d.%m.%Y"))), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_spend_weekly -->

<!-- # saveWidget(plot_spend_weekly, file = paste0(directory, "/plot_spend_weekly.html")) -->
<!-- ``` -->

<!-- Column {.tabset .mobile} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### **SPENDING OVER TIME** -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   time_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     mutate( -->
<!--       ad_creation_time_week = as.Date(cut( -->
<!--         ad_creation_time, -->
<!--         breaks = "week", -->
<!--         start.on.monday = TRUE -->
<!--       )) + 6, -->
<!--       cumulative_spend_million = round((cumulative_spend / 1000000), digits = 3) -->
<!--     ) %>% -->
<!--     group_by(page_name, ad_creation_time_week) %>% -->
<!--     summarise(end_of_week_million_spend = max(cumulative_spend_million)) %>% -->
<!--     ungroup() %>% -->
<!--     ggplot( -->
<!--       aes(x = ad_creation_time_week, y = end_of_week_million_spend, color = page_name) -->
<!--     ) + -->
<!--     geom_line() + -->
<!--     geom_point(size = 0.8, aes(text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Week:", -->
<!--       ad_creation_time_week, -->
<!--       "<br>Cumulative spend:", -->
<!--       end_of_week_million_spend, "million CZK" -->
<!--     ))) + -->
<!--     geom_vline( -->
<!--       aes(xintercept = as.numeric(election_date)), -->
<!--       color = "#563a3a", -->
<!--       linetype = 2, -->
<!--       size = 0.2 -->
<!--     ) + -->
<!--     geom_text( -->
<!--       aes(x = election_date, y = 0, label = "elections"), -->
<!--       color = "#22209F", -->
<!--       vjust = -1, -->
<!--       size = 3, -->
<!--       fontface = "bold", -->
<!--       check_overlap = TRUE -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 5, 0.25), -->
<!--       labels = seq(0, 5, 0.25) -->
<!--     ) + -->
<!--     scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") + -->
<!--     coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) + -->
<!--     theme( -->
<!--       legend.title = element_blank(), -->
<!--       axis.text.x = element_text(angle = 45, hjust = 1) -->
<!--     ) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(color = ""), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->
<!-- ``` -->

<!-- ### **SPENDING WEEKLY** -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   time_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     mutate( -->
<!--       end_of_week = as.Date(cut(ad_creation_time, breaks = "week", start.on.monday = TRUE)) + 6, -->
<!--     ) %>% -->
<!--     group_by(page_name, end_of_week) %>% -->
<!--     summarise(by_week_thousands_spend = round(sum(avg_spend) / 1000, digits = 0)) %>% -->
<!--     ungroup() %>% -->
<!--     ggplot(aes( -->
<!--       x = end_of_week, y = by_week_thousands_spend, fill = page_name, -->
<!--       text = paste( -->
<!--         "Page:", -->
<!--         page_name, -->
<!--         "<br>Week:", -->
<!--         end_of_week, -->
<!--         "<br>Weekly spend:", -->
<!--         by_week_thousands_spend, "thousand CZK" -->
<!--       ) -->
<!--     )) + -->
<!--     geom_col(width = 5.5) + -->
<!--     geom_vline(xintercept = as.numeric(election_date), color = "#563a3a", linetype = 2, size = 0.2) + -->
<!--     geom_text(aes(x = election_date, y = 0, label = "elections"), color = "#22209F", vjust = -1, size = 3, fontface = "bold", check_overlap = TRUE) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 5000, 250), -->
<!--       labels = seq(0, 5000, 250) -->
<!--     ) + -->
<!--     scale_x_date(date_breaks = "1 months", date_labels = "%d.%m.%y") + -->
<!--     coord_cartesian(xlim = c(start_date, end_date), expand = TRUE) + -->
<!--     theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1)) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = ""), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->
<!-- ``` -->

<!-- Audience -->
<!-- ===================================== -->

<!-- Column {.tabset} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### **GENDER** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_gender <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, avg_male)) %>% -->
<!--     ggplot(aes(x = avg_male, y = page_name, fill = avg_male, text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Proportion of male audience:", -->
<!--       avg_male * 100, "%" -->
<!--     ))) + -->
<!--     geom_col() + -->
<!--     geom_vline(aes(xintercept = 0.5, color = "#db0b50")) + -->
<!--     scale_fill_gradient( -->
<!--       low = "#db1d0b", high = "#03457f", -->
<!--     ) + -->
<!--     scale_x_continuous( -->
<!--       limits = c(0, 1), -->
<!--       breaks = seq(0, 1, 0.25), -->
<!--       labels = c("0%", "25%", "50%", "75%", "100%"), -->
<!--       expand = c(0, 0) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     xlab("Proportion of ads targeting male audience") + -->
<!--     ylab(element_blank()) + -->
<!--     ggtitle(paste("Gender targeting of top 30 spenders since", format(start_date, "%d.%m.%Y"))), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_gender -->

<!-- # saveWidget(plot_gender, file = paste0(directory, "/plot_gender.html")) -->
<!-- ``` -->

<!-- ### **AGE** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_age <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     select( -->
<!--       page_name, -->
<!--       avg_18_24, -->
<!--       avg_25_34, -->
<!--       avg_35_44, -->
<!--       avg_45_54, -->
<!--       avg_55_64, -->
<!--       avg_65_plus -->
<!--     ) %>% -->
<!--     pivot_longer(cols = 2:7, names_to = "age_group", values_to = "proportion", values_drop_na = TRUE) %>% -->
<!--     ggplot(aes(x = age_group, y = proportion, fill = page_name, text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Proportion:", -->
<!--       proportion * 100, "% (out of 100 %)" -->
<!--     ))) + -->
<!--     geom_col(position = "dodge2") + -->
<!--     scale_x_discrete(labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")) + -->
<!--     scale_fill_brewer(palette = "Paired") + -->
<!--     scale_y_continuous( -->
<!--       limits = c(0, 0.5), -->
<!--       breaks = seq(0, 0.5, 0.1), -->
<!--       labels = c("0%", "10%", "20%", "30%", "40%", "50%") -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.title = element_blank()) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "") + -->
<!--     ggtitle(paste("Age of audience of top 10 spenders since", format(start_date, "%d.%m.%Y"))), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_age -->

<!-- # saveWidget(plot_age, file = paste0(directory, "/plot_age.html")) -->
<!-- ``` -->

<!-- ### **GENDER & AGE SUMMARY TABLE** {.no-mobile} -->

<!-- ```{r} -->
<!-- summary_dataset %>% -->
<!--   select(c(1:2), 14:36) %>% -->
<!--   setNames(gsub("avg_", "", names(.))) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef(filterable = FALSE, format = colFormat(percent = TRUE, digits = 1)), -->
<!--     columns = list( -->
<!--       "page_name" = colDef(name = "Page Name", filterable = TRUE, width = 120), -->
<!--       "page_id" = colDef(name = "Page ID", width = 120), -->
<!--       "female_65_plus" = colDef(width = 110) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->

<!-- ### **REGIONAL** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_region <- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     select( -->
<!--       page_name, -->
<!--       avg_pha, -->
<!--       avg_stc, -->
<!--       avg_jhc, -->
<!--       avg_plk, -->
<!--       avg_kvk, -->
<!--       avg_ulk, -->
<!--       avg_lbk, -->
<!--       avg_hkk, -->
<!--       avg_pak, -->
<!--       avg_vys, -->
<!--       avg_jhm, -->
<!--       avg_olk, -->
<!--       avg_msk, -->
<!--       avg_zlk -->
<!--     ) %>% -->
<!--     pivot_longer(cols = 2:15, names_to = "region_group", values_to = "proportion", values_drop_na = TRUE) %>% -->
<!--     ggplot(aes(x = region_group, y = proportion, fill = page_name, text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Proportion:", -->
<!--       proportion * 100, "% (out of 100 %)" -->
<!--     ))) + -->
<!--     geom_col(position = "dodge2") + -->
<!--     scale_x_discrete(labels = c("HKK", "JHC", "JHM", "KVK", "LBK", "MSK", "OLK", "PAK", "PHA", "PLK", "STC", "ULK", "VYS", "ZLK")) + -->
<!--     scale_fill_brewer(palette = "Paired") + -->
<!--     scale_y_continuous( -->
<!--       limits = c(0, 0.5), -->
<!--       breaks = seq(0, 0.5, 0.1), -->
<!--       labels = c("0%", "10%", "20%", "30%", "40%", "50%") -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.title = element_blank()) + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "") + -->
<!--     ggtitle(paste("Regions of audience of ads of top 10 spenders since", format(start_date, "%d.%m.%Y"))), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_region -->

<!-- # saveWidget(plot_region, file = paste0(directory, "/plot_region.html")) -->
<!-- ``` -->


<!-- ### **REGION SUMMARY TABLE** {.no-mobile} -->

<!-- ```{r} -->
<!-- summary_dataset %>% -->
<!--   select(c(1:2), 37:ncol(.)) %>% -->
<!--   setNames(gsub("avg_", "", names(.))) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef(filterable = FALSE, format = colFormat(percent = TRUE, digits = 1)), -->
<!--     columns = list( -->
<!--       "page_name" = colDef(name = "Page Name", sticky = "left", filterable = TRUE, width = 120), -->
<!--       "page_id" = colDef(name = "Page ID", sticky = "left", width = 120) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->


<!-- ### **TOP SPENDERS BY REGION** {.no-mobile} -->

<!-- ```{r} -->
<!-- plot_top_spenders_by_region <- ggplotly( -->
<!--   regional_spenders %>% -->
<!--     group_by(region) %>% -->
<!--     slice_max(regional_spend, n = 10) %>% -->
<!--     ungroup() %>% -->
<!--     mutate( -->
<!--       regional_spend_1000 = round(regional_spend / 1000, 0), -->
<!--       page_name = reorder(page_name, regional_spend_1000) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = region, -->
<!--         y = regional_spend_1000, -->
<!--         fill = page_name, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Regional spend:", -->
<!--           regional_spend_1000, -->
<!--           "thousand CZK" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col(position = "dodge2") + -->
<!--     scale_x_discrete( -->
<!--       labels = c( -->
<!--         "HKK", -->
<!--         "JHC", -->
<!--         "JHM", -->
<!--         "KVK", -->
<!--         "LBK", -->
<!--         "MSK", -->
<!--         "OLK", -->
<!--         "PAK", -->
<!--         "PHA", -->
<!--         "PLK", -->
<!--         "STC", -->
<!--         "ULK", -->
<!--         "VYS", -->
<!--         "ZLK" -->
<!--       ) -->
<!--     ) + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 1000, 100), -->
<!--       labels = seq(0, 1000, 100) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.title = element_blank(), legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab("CZK thousand") + -->
<!--     labs(fill = "") + -->
<!--     ggtitle( -->
<!--       paste( -->
<!--         "Top 10 spenders in each region since", -->
<!--         format(start_date, "%d.%m.%Y") -->
<!--       ) -->
<!--     ), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displaylogo = FALSE) -->

<!-- plot_top_spenders_by_region -->

<!-- # saveWidget(plot_top_spenders_by_region, file = paste0(directory, "/plot_top_spenders_by_region.html")) -->
<!-- ``` -->


<!-- ### **TOP SPENDERS BY REGION TABLE** {.no-mobile} -->

<!-- ```{r} -->
<!-- regional_spenders %>% -->
<!--   pivot_wider(names_from = "region", values_from = "regional_spend") %>% -->
<!--   setNames(gsub("avg_", "", names(.))) %>% -->
<!--   select( -->
<!--     "page_name", -->
<!--     "page_id", -->
<!--     "hkk", -->
<!--     "jhc", -->
<!--     "jhm", -->
<!--     "kvk", -->
<!--     "lbk", -->
<!--     "msk", -->
<!--     "olk", -->
<!--     "pak", -->
<!--     "pha", -->
<!--     "plk", -->
<!--     "stc", -->
<!--     "ulk", -->
<!--     "vys", -->
<!--     "zlk" -->
<!--   ) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef( -->
<!--       filterable = FALSE, -->
<!--       format = colFormat( -->
<!--         prefix = "CZK ", -->
<!--         separators = TRUE, -->
<!--         digits = 0 -->
<!--       ) -->
<!--     ), -->
<!--     columns = list( -->
<!--       "page_name" = colDef( -->
<!--         name = "Page Name", -->
<!--         sticky = "left", -->
<!--         width = 120, -->
<!--         format = colFormat() -->
<!--       ), -->
<!--       "page_id" = colDef( -->
<!--         name = "Page ID", -->
<!--         sticky = "left", -->
<!--         width = 120, -->
<!--         format = colFormat() -->
<!--       ) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->

<!-- Column {.tabset .mobile} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### **GENDER** -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(total_ads > 10) %>% -->
<!--     slice_max(avg_spend, n = 30) %>% -->
<!--     mutate(page_name = reorder(page_name, avg_male)) %>% -->
<!--     ggplot(aes(x = avg_male, y = page_name, fill = avg_male, text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Proportion of male audience:", -->
<!--       avg_male * 100, "%" -->
<!--     ))) + -->
<!--     geom_col() + -->
<!--     geom_vline(aes(xintercept = 0.5, color = "#db0b50")) + -->
<!--     scale_fill_gradient( -->
<!--       low = "#db1d0b", high = "#03457f", -->
<!--     ) + -->
<!--     scale_x_continuous( -->
<!--       limits = c(0, 1), -->
<!--       breaks = seq(0, 1, 0.25), -->
<!--       labels = c("0%", "25%", "50%", "75%", "100%"), -->
<!--       expand = c(0, 0) -->
<!--     ) + -->
<!--     scale_y_discrete(label = function(x) str_trunc(x, 16)) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->
<!-- ``` -->

<!-- ### **AGE** -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     select( -->
<!--       page_name, -->
<!--       avg_18_24, -->
<!--       avg_25_34, -->
<!--       avg_35_44, -->
<!--       avg_45_54, -->
<!--       avg_55_64, -->
<!--       avg_65_plus -->
<!--     ) %>% -->
<!--     pivot_longer(cols = 2:7, names_to = "age_group", values_to = "proportion", values_drop_na = TRUE) %>% -->
<!--     ggplot(aes(x = age_group, y = proportion, fill = page_name, text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Proportion:", -->
<!--       proportion * 100, "% (out of 100 %)" -->
<!--     ))) + -->
<!--     geom_col(position = "dodge2") + -->
<!--     scale_x_discrete(labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+")) + -->
<!--     scale_fill_brewer(palette = "Paired") + -->
<!--     scale_y_continuous( -->
<!--       limits = c(0, 0.5), -->
<!--       breaks = seq(0, 0.5, 0.1), -->
<!--       labels = c("0%", "10%", "20%", "30%", "40%", "50%") -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.title = element_blank(), legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "") +  -->
<!--     coord_flip(), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->

<!-- ### **GENDER & AGE SUMMARY TABLE** -->

<!-- ```{r} -->
<!-- summary_dataset %>% -->
<!--   select(c(1:2), 14:36) %>% -->
<!--   setNames(gsub("avg_", "", names(.))) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef(filterable = FALSE, format = colFormat(percent = TRUE, digits = 1)), -->
<!--     columns = list( -->
<!--       "page_name" = colDef(name = "Page Name", filterable = TRUE, width = 70), -->
<!--       "page_id" = colDef(name = "Page ID", width = 50), -->
<!--       "female_65_plus" = colDef(width = 110) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->

<!-- ### **REGIONAL** -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   summary_dataset %>% -->
<!--     filter(page_id %in% top_10_spenders$page_id) %>% -->
<!--     select( -->
<!--       page_name, -->
<!--       avg_pha, -->
<!--       avg_stc, -->
<!--       avg_jhc, -->
<!--       avg_plk, -->
<!--       avg_kvk, -->
<!--       avg_ulk, -->
<!--       avg_lbk, -->
<!--       avg_hkk, -->
<!--       avg_pak, -->
<!--       avg_vys, -->
<!--       avg_jhm, -->
<!--       avg_olk, -->
<!--       avg_msk, -->
<!--       avg_zlk -->
<!--     ) %>% -->
<!--     pivot_longer(cols = 2:15, names_to = "region_group", values_to = "proportion", values_drop_na = TRUE) %>% -->
<!--     ggplot(aes(x = region_group, y = proportion, fill = page_name, text = paste( -->
<!--       "Page:", -->
<!--       page_name, -->
<!--       "<br>Proportion:", -->
<!--       proportion * 100, "% (out of 100 %)" -->
<!--     ))) + -->
<!--     geom_col(position = "dodge2") + -->
<!--     scale_x_discrete(labels = c("HKK", "JHC", "JHM", "KVK", "LBK", "MSK", "OLK", "PAK", "PHA", "PLK", "STC", "ULK", "VYS", "ZLK")) + -->
<!--     scale_fill_brewer(palette = "Paired") + -->
<!--     scale_y_continuous( -->
<!--       limits = c(0, 0.5), -->
<!--       breaks = seq(0, 0.5, 0.1), -->
<!--       labels = c("0%", "10%", "20%", "30%", "40%", "50%") -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.title = element_blank(), legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "") +  -->
<!--     coord_flip(), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->


<!-- ### **REGION SUMMARY TABLE** -->

<!-- ```{r} -->
<!-- summary_dataset %>% -->
<!--   select(c(1:2), 37:ncol(.)) %>% -->
<!--   setNames(gsub("avg_", "", names(.))) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef(width = 55, filterable = FALSE, format = colFormat(percent = TRUE, digits = 1)), -->
<!--     columns = list( -->
<!--       "page_name" = colDef(name = "Page Name", sticky = "left", filterable = TRUE, width = 70), -->
<!--       "page_id" = colDef(name = "Page ID", sticky = "left", width = 50) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->


<!-- ### **TOP SPENDERS BY REGION** -->

<!-- ```{r} -->
<!-- ggplotly( -->
<!--   regional_spenders %>% -->
<!--     group_by(region) %>% -->
<!--     slice_max(regional_spend, n = 10) %>% -->
<!--     ungroup() %>% -->
<!--     mutate( -->
<!--       regional_spend_1000 = round(regional_spend / 1000, 0), -->
<!--       page_name = reorder(page_name, regional_spend_1000) -->
<!--     ) %>% -->
<!--     ggplot( -->
<!--       aes( -->
<!--         x = region, -->
<!--         y = regional_spend_1000, -->
<!--         fill = page_name, -->
<!--         text = paste( -->
<!--           "Page:", -->
<!--           page_name, -->
<!--           "<br>Regional spend:", -->
<!--           regional_spend_1000, -->
<!--           "thousand CZK" -->
<!--         ) -->
<!--       ) -->
<!--     ) + -->
<!--     geom_col(position = "dodge2") + -->
<!--     scale_x_discrete( -->
<!--       labels = c( -->
<!--         "HKK", -->
<!--         "JHC", -->
<!--         "JHM", -->
<!--         "KVK", -->
<!--         "LBK", -->
<!--         "MSK", -->
<!--         "OLK", -->
<!--         "PAK", -->
<!--         "PHA", -->
<!--         "PLK", -->
<!--         "STC", -->
<!--         "ULK", -->
<!--         "VYS", -->
<!--         "ZLK" -->
<!--       ) -->
<!--     ) + -->
<!--     scale_y_continuous( -->
<!--       breaks = seq(0, 1000, 100), -->
<!--       labels = seq(0, 1000, 100) -->
<!--     ) + -->
<!--     theme_minimal() + -->
<!--     theme(legend.title = element_blank(), legend.position = "none") + -->
<!--     xlab(element_blank()) + -->
<!--     ylab(element_blank()) + -->
<!--     labs(fill = "") + -->
<!--     coord_flip(), -->
<!--   tooltip = "text" -->
<!-- ) %>% -->
<!--   config(displayModeBar = FALSE) -->

<!-- ``` -->


<!-- ### **TOP SPENDERS BY REGION TABLE** -->

<!-- ```{r} -->
<!-- regional_spenders %>% -->
<!--   pivot_wider(names_from = "region", values_from = "regional_spend") %>% -->
<!--   setNames(gsub("avg_", "", names(.))) %>% -->
<!--   select( -->
<!--     "page_name", -->
<!--     "page_id", -->
<!--     "hkk", -->
<!--     "jhc", -->
<!--     "jhm", -->
<!--     "kvk", -->
<!--     "lbk", -->
<!--     "msk", -->
<!--     "olk", -->
<!--     "pak", -->
<!--     "pha", -->
<!--     "plk", -->
<!--     "stc", -->
<!--     "ulk", -->
<!--     "vys", -->
<!--     "zlk" -->
<!--   ) %>% -->
<!--   reactable( -->
<!--     defaultPageSize = 15, -->
<!--     theme = nytimes(), -->
<!--     highlight = TRUE, -->
<!--     defaultSorted = c("page_name"), -->
<!--     filterable = TRUE, -->
<!--     striped = TRUE, -->
<!--     defaultColDef = colDef( -->
<!--       filterable = FALSE, -->
<!--       format = colFormat( -->
<!--         prefix = "CZK ", -->
<!--         separators = TRUE, -->
<!--         digits = 0 -->
<!--       ) -->
<!--     ), -->
<!--     columns = list( -->
<!--       "page_name" = colDef( -->
<!--         name = "Page Name", -->
<!--         sticky = "left", -->
<!--         width = 120, -->
<!--         format = colFormat() -->
<!--       ), -->
<!--       "page_id" = colDef( -->
<!--         name = "Page ID", -->
<!--         sticky = "left", -->
<!--         width = 120, -->
<!--         format = colFormat() -->
<!--       ) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r cleanup, include=FALSE} -->
<!-- # Because the saveWidget function does not correctly delete the dependency files -->
<!-- # which are used to create individual self-sustaining widgets, we have to delete -->
<!-- # them using R functions. All non-html files in output folder are deleted. -->

<!-- unlink(grep( -->
<!--   x = list.files( -->
<!--     path = directory, -->
<!--     recursive = TRUE, -->
<!--     full.names = TRUE -->
<!--   ), -->
<!--   pattern = "(.html)$", -->
<!--   invert = TRUE, -->
<!--   value = TRUE -->
<!-- )) -->
<!-- ``` -->


<!-- Using TsParticles -->
<!-- <script src="https://cdn.jsdelivr.net/npm/tsparticles-preset-snow@2/tsparticles.preset.snow.bundle.min.js"></script> -->
<!-- <script type="text/javascript"> -->

<!-- (async () => { -->
<!--   await tsParticles.load("tsparticles", { -->
<!--       "background": { -->
<!--         "color": "#0064ff", -->
<!--         "image": "", -->
<!--         "position": "50% 50%", -->
<!--         "repeat": "no-repeat", -->
<!--         "size": "cover" -->
<!--     }, -->
<!--     preset: "snow", -->
<!--   }); -->
<!-- })(); -->


<!-- </script> -->





